"""Add Broker

Revision ID: 75a59fa2e79
Revises: 236f63c96b6a
Create Date: 2015-03-20 14:33:50.045822

"""

# revision identifiers, used by Alembic.
revision = '75a59fa2e79'
down_revision = '236f63c96b6a'

from alembic import op
import sqlalchemy as sa

from cue.db.sqlalchemy import types


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', types.UUID(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_metadata',
    sa.Column('id', types.UUID(), nullable=False),
    sa.Column('broker_id', types.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_metadata')
    op.drop_table('brokers')
    ### end Alembic commands ###